version: "2"

services:
  postgres:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=greenHouse
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
